version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - mydb-volume:/var/lib/postgresql/data
    networks:
      - mynetwork

  redis:
    image: redis:latest
    networks:
      - mynetwork

  webapp:
    build: rust-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - mynetwork

volumes:
  mydb-volume:

networks:
  mynetwork: