version: '3'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ShooterDB
    volumes:
      - mydb-shootervolume:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

  redis:
    image: redis:latest
    networks:
      - mynetwork

  webapp:
    build: rust-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - mynetwork
    env_file:
      - ./rust-api/.env

volumes:
  mydb-shootervolume:

networks:
  mynetwork: