[package]
name = "rust-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.1.0", features = ["postgres"] }
actix-web = "4"
dotenvy = "0.15"
jsonwebtoken = "7.2.0"
bcrypt = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "0.8", features = ["v4"] }
argon2 = { version = "0.5.3" }
chrono = "0.4.37"